FROM hkjeon13/ubuntu:18.04

RUN apt-get update
RUN apt-get install -y python3.8 python3-pip python3-dev build-essential libssl-dev wget

RUN wget https://www.python.org/ftp/python/3.7.5/Python-3.7.5.tgz
RUN tar -xvf Python-3.7.5.tgz
WORKDIR Python-3.7.5
RUN ./configure --enable-optimizations
RUN make install
WORKDIR ../
RUN wget https://www.python.org/ftp/python/3.9.5/Python-3.9.5.tgz
RUN tar -xvf Python-3.9.5.tgz
WORKDIR Python-3.9.5
RUN ./configure --enable-optimizations
RUN make install
WORKDIR ../
RUN wget https://www.python.org/ftp/python/3.10.5/Python-3.10.5.tgz
RUN tar -xvf Python-3.10.5.tgz
WORKDIR Python-3.10.5
RUN ./configure --enable-optimizations
RUN make install
WORKDIR ../
RUN python -m pip install --upgrade pip
RUN apt-get install -y git
RUN git clone https://github.com/hkjeon13/koai.git
WORKDIR /koai
RUN python -m pip install -r requirements.txt