FROM hkjeon13/ubuntu:20.04-koai

RUN git clone https://github.com/hkjeon13/koai.git
WORKDIR koai/

RUN python3.7 setup.py bdist_wheel
RUN python3.8 setup.py bdist_wheel
RUN python3.9 setup.py bdist_wheel
RUN python3.10 setup.py bdist_wheel

RUN python3 -m auditwheel repair dist/koai-*-cp*-cp*-linux*.whl --plat manylinux_2_34_aarch64