FROM hkjeon13/ubuntu:20.04-koai
RUN git clone https://github.com/hkjeon13/koai.git
WORKDIR koai/
RUN git fetch --all && git pull origin main
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

RUN python3.8 setup.py bdist_wheel && \
    python3.8 setup.py bdist_wheel && \
    python3 -m auditwheel repair dist/koai-*-cp*-cp*-linux*.whl --plat manylinux_2_34_x86_64